//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoinU
    {
        public int ApplicationID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> ExperienceYears { get; set; }
        public string CoverLetter { get; set; }
        public Nullable<System.DateTime> SubmittedAt { get; set; }
        public string ApplicationStatus { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Nationality { get; set; }
        public string MaritalStatus { get; set; }
        public string Address { get; set; }
        public string MedicalConditions { get; set; }
        public Nullable<bool> EligibleToWorkInJordan { get; set; }
        public Nullable<bool> ValidDrivingLicense { get; set; }
        public string NannyType { get; set; }
        public Nullable<bool> WillingToTravel { get; set; }
        public Nullable<bool> WillingToWorkWeekends { get; set; }
        public Nullable<bool> FlexibleHours { get; set; }
        public string CurrentWork { get; set; }
        public string ExperienceTypes { get; set; }
        public Nullable<bool> JoinCompany { get; set; }
        public Nullable<bool> RegisteredWithOtherAgency { get; set; }
        public string OtherAgencies { get; set; }
        public Nullable<bool> ConsentToDataProcessing { get; set; }
        public string Disclaimer { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public string LicensePath { get; set; }
    }
}
