//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceDetail()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int DetailID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string DetailType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<bool> StartDateFlexible { get; set; }
        public string Days { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string Duration { get; set; }
        public string Frequency { get; set; }
        public string ScheduleType { get; set; }
        public string SpecialNeedsTypes { get; set; }
        public string AdditionalInfo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Service Service { get; set; }
    }
}
