//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonial
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string statues { get; set; }
        public Nullable<bool> TestimonialSubmitted { get; set; }
        public Nullable<int> BookingID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Booking Booking { get; set; }
    }
}
